### ISSUE TITLE
I think someone already tried this (unless I'm mistaken....)

### ISSUE THREAD

**Issue by DumbJoe** [ericblade/vscode-unrealscript#1]
His link: https://github.com/robojumper/UnVSCript 

Also according to wikipedia, there are some things that don't work for it....

EDIT [here](https://en.m.wikipedia.org/wiki/Unreal_Engine):

> Similar to Java, UnrealScript is object-oriented without multiple inheritance (classes all inherit from a common Object class), and classes are defined in individual files named for the class they define. Unlike Java, UnrealScript does not have object wrappers for primitive types. Interfaces are only supported in Unreal Engine generation 3 and a few Unreal Engine 2 games. UnrealScript supports operator overloading, but not method overloading, except for optional parameters.

**Comment by ericblade** [comment]
Thank you for the link. I did not find that in the extension search, not sure if it's published anywhere or not.

**Comment by DumbJoe** [comment]
Yeah probably isn't.....the only thing he has added is skeleton Language Server (for autocompletion, goto definition, etc.) but never got around to do any real work on it....

Maybe you two could like collab and make one best uscript plugin? hahaha

**Comment by ericblade** [comment]
That would be pretty cool if anyone were actually writing anything in Unrealscript these days.  I don't know of anyone who is, but I did need to refer to some old code a while back, and it was tough to read it without any syntax highlighting.  I would like to add ability to run ucc make, but i haven't found anyone who knows the answer to how to correctly add a build step to a language via extension, and i haven't had time with my regular job, to go messing around with it.

Frankly, I'd still recommend WOTgreal as a good Unrealscript editor, although it has suffered a lot from not being maintained for many years now.  I do wonder, now that I'm thinking about it, if WOTgreal's language files could somehow be used with VSC.  

I did want to go and rebuild a bunch of mods I made for an Unreal2 game, over the holidays when I had a bunch of free time, and that's why I was looking at my old code, which inspired me to add this extension for syntax highlighting, because looking at a huge UC file with no highlighting was weird.

**Comment by DumbJoe** [comment]
> That would be pretty cool if anyone were actually writing anything in Unrealscript these days.  I don't know of anyone who is, but I did need to refer to some old code a while back, and it was tough to read it without any syntax highlighting.

Well I wanna learn how to write something in Uscript.........and seeing text in black and white isn't exactly encouraging either....hahaha So that's someone! Hahaha.... Oh yeah and if you look at the Killing Floor community, there are plenty(Or a few I should say wouldn't say plenty as they mostly died out...hahaha which is still something!) who still mod for the game.....but unsure if they use Visual Studio Code or just Windows NotePad and deal with the black and white text.....

I've seen a lot of mods for a game called Killing Floor that I would like fixed up(or completely remake from ground up - if it's so badly written or I can't be arsed fixing their code...haha) whenever I can as I still play this 10 year old game..... Some of the modders have left the scene and when I ask them to fix they say no(or completely ignore me) because they no longer play the game or and uninterested anymore leaving me and others who still use their mod in the dust...because something is broken.....or not enough features...haha...

 The only issue, besides this is getting into it.......I have no prior programming experience.....and as my bio/name suggests, I actually do leech off other people's work...mainly because of that...hahaha, and never contribute....except when giving feedback, as I guess that counts as contributing? 

> I did want to go and rebuild a bunch of mods I made for an Unreal2 game

What game's this? Out of curiosity of course....

**Comment by ericblade** [comment]
It was a game called Land of the Dead.  It's about 12 years old now or something, and people are still playing it on PC.

**Comment by DumbJoe** [comment]
Land of the Dead: Road to Fiddler's Green, the one released in 2005? Wow that's old...older (maybe as I wasn't around when this happened...) than the KFMod itself that was for UT2004.....

There was a couple or so maps done from that for KF unless it was taken from the movie equivalent....

**Comment by ericblade** [comment]
Yeah, that's the one. guess it's 14 years now. :-D yeah people are still playing it, not as much as a few years ago, though.  There's been some issues with the servers that people are running, a lot of people have totally screwed up their mods and their redirect servers, so most of the MP servers appear broken to me and others.

**Comment by DumbJoe** [comment]
Damn you modders running away from your obligations! hahahaha It's like you having a child with your dear wife(but then she unfortunately dies giving birth) and then run away because you no longer want to support him..... 

"I'm sorry, I am no longer interested in my son/daughter, so I will not longer be improving him anytime soon." 
"Sorry, my work with him/her is now done, goodbye."
<No reply/ignored>
"If you would like to carry on my legacy, you can have my son/daughter's source so you can do him/her up however you want; unfortunately I do not have the time or the interest at this current moment in time to work on it but here have my son/daughter as it is so you do some more testing on him/her - goodluck!"
